'use client'

import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
} from '@/components/ui/card'

import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar'

const testimonials = [
  {
    name: 'Rapha',
    avatar: 'E',
    title: 'Web Developer',
    description:
      "I've seen a significant improvement in my website's user experience after using this platform. It's a game-changer!",
  },
  {
    name: 'Joey',
    avatar: 'N',
    title: 'Front-end Developer',
    description:
      'This tool has been an incredible asset for refining and enhancing the UI of my projects. Highly recommended!',
  },
  {
    name: 'Sophia',
    avatar: 'S',
    title: 'UX Designer',
    description:
      "I can't imagine my design process without this platform. It provides invaluable insights and feedback for creating superior user experiences.",
  },
  {
    name: 'David',
    avatar: 'D',
    title: 'Product Manager',
    description:
      "Our team's productivity has surged, and our websites have vastly improved in response to the feedback generated by this remarkable platform. It's a game-changer!",
  },
]

export const LandingContent = () => {
  return (
    <div className='px-10 pb-20'>
      <h2 className='text-center text-4xl text-white font-extrabold mb-10'>
        Testimonials
      </h2>
      <div className='grid grid-cols-1 sm:grid-cols-2 gap-4'>
        {testimonials.map((item) => (
          <Card
            key={item.description}
            className='bg-[#192339] border-none text-white'
          >
            <CardHeader>
              <CardTitle className='flex items-center gap-x-2'>
                <Avatar>
                  <AvatarImage src='https://github.com/shadcn.png' />
                  <AvatarFallback>CN</AvatarFallback>
                </Avatar>
                <div>
                  <p className='text-lg'>{item.name}</p>
                  <p className='text-zinc-400 text-sm'>{item.title}</p>
                </div>
              </CardTitle>
              <CardContent className='pt-4 px-0'>
                {item.description}
              </CardContent>
            </CardHeader>
          </Card>
        ))}
      </div>
    </div>
  )
}
